### PR TITLE
Add timestamp interpolation to the log file path

### PR DESCRIPTION
**Pull request by cpennington**

### CODE REVIEW

**Comment by cpennington** [comment]
@estute @jzoldak: Can I get a review?

This should match https://github.com/edx/configuration/pull/3254 and https://github.com/edx/edx-platform/pull/13021

**Comment by jzoldak** [comment]
Would be nice to add to the readme, including an example.
Oh, and if you are there I noticed some typos s/timestame/timestamp.

**Comment by jzoldak** [comment]
Nit on README. Your call. 👍 for merging this in.

**Comment by cpennington** [comment]
@jzoldak: Updated. I'm going to go ahead and merge now.

**Pull request merged**
